"""
Captions live in text, not burned into the figures.

WHY THIS MODULE EXISTS
----------------------
Every figure in this project used to carry its own explanatory footnote, set in
small grey type under the axes. That is the wrong home for it twice over: a
journal sets the caption itself, so the text arrives duplicated and the two
copies immediately disagree; and a footnote sized to be unobtrusive is a
footnote nobody reading a printed column can actually read.

Deleting the strings was not the answer either. Those sentences carry the
caveats that keep each figure honest -- that the daily temporal closure holds by
construction rather than by evidence, that within-mascon spread is a lower
bound, that SHAP shows association and not cause. Losing them would leave a set
of figures that overclaim by omission.

So the text stays exactly where it was written, beside the code that knows what
the figure contains, and this module carries it OUT of the image and INTO a
Markdown file next to the figures. One source, two consumers: nothing to keep in
sync by hand, and nothing rendered in six-point grey.

HOW A FIGURE FUNCTION USES IT
-----------------------------
Where it used to call `fig.text(...)`, it calls `record()` instead::

    figure_captions.record(out_path, 'Agreement here is EXACT BY CONSTRUCTION ...')
    fig.savefig(out_path, ...)

and once a script has drawn everything, its `main()` flushes the file::

    figure_captions.write_index(out_dir)

`record` keys on the figure's own path, so a caption cannot outlive the figure
it belongs to or attach itself to the wrong one. Captions are written per output
directory, each file owned by the script that filled it -- no merging across
scripts, so two pipeline steps writing figures at the same time cannot race.
"""

from __future__ import annotations

import os
import re
from typing import Dict, List, Tuple

# figure path -> caption, in the order the figures were drawn.
_COLLECTED: Dict[str, str] = {}

CAPTIONS_FILE = 'CAPTIONS.md'


def record(fig_path: str, caption: str) -> None:
    """
    Attach a caption to the figure at `fig_path`.

    Whitespace is collapsed: these strings are written as wrapped Python source
    literals, so they arrive carrying the newlines and indentation of the file
    they were typed in rather than of the sentence they express.
    """
    if not caption:
        return
    _COLLECTED[os.path.abspath(fig_path)] = re.sub(r'\s+', ' ', caption).strip()


def clear() -> None:
    """Forget everything recorded so far. For tests, and for repeated runs."""
    _COLLECTED.clear()


def collected() -> List[Tuple[str, str]]:
    """Recorded (path, caption) pairs, in insertion order."""
    return list(_COLLECTED.items())


def write_index(out_dir: str, title: str = 'Figure captions',
                preamble: str = '') -> str:
    """
    Write every caption recorded for figures in `out_dir` to `out_dir/CAPTIONS.md`.

    Only figures that actually landed in this directory are written, so a script
    producing figures in two places gets one file in each rather than one file
    listing figures the reader cannot find beside it.
    """
    out_dir = os.path.abspath(out_dir)
    rows = [(p, c) for p, c in _COLLECTED.items()
            if os.path.dirname(p) == out_dir]
    path = os.path.join(out_dir, CAPTIONS_FILE)
    if not rows:
        return path

    lines = [f'# {title}', '',
             'Generated by `figure_captions.write_index`. Edit the caption in the '
             'script that draws the figure, not here — this file is overwritten '
             'on every run.', '']
    if preamble:
        lines += [preamble, '']
    for p, c in rows:
        lines += [f'**`{os.path.basename(p)}`**', '', c, '']

    os.makedirs(out_dir, exist_ok=True)
    with open(path, 'w') as f:
        f.write('\n'.join(lines).rstrip() + '\n')
    return path
