#!/usr/bin/env bash
# Complete regeneration of every result in the project, from raw inputs.
#
#   ./run_full_pipeline.sh                 # analysis only (inputs must already exist)
#   ./run_full_pipeline.sh --with-download # also re-download from Earth Engine (~30 min, ~5 GB)
#   ./run_full_pipeline.sh --check         # preflight only: report what is missing, run nothing
#
# Two classes of step, deliberately handled differently:
#
#   require <cmd>   ABORTS the whole script on failure. Used for anything later
#                   steps depend on. A failed target or cube must never be
#                   followed by ten steps quietly consuming a stale file.
#   run <cmd>       logs and CONTINUES. Used only for leaf steps whose failure
#                   cannot corrupt anything downstream.
#
# The old version used `run` for everything, so a failed step 0 would leave every
# subsequent step reading a stale or absent GRACE target and still report success.
set -uo pipefail
cd "$(dirname "$0")"
LOG="run_full_pipeline.log"
: > "$LOG"

WITH_DOWNLOAD=0
CHECK_ONLY=0
for arg in "$@"; do
  case "$arg" in
    --with-download) WITH_DOWNLOAD=1 ;;
    --check)         CHECK_ONLY=1 ;;
    *) echo "unknown option: $arg" >&2; exit 2 ;;
  esac
done

say () { echo -e "$*" | tee -a "$LOG"; }
run () { say "\n>>> $*"; "$@" >>"$LOG" 2>&1 && say "    OK" || say "    FAILED (continuing)"; }
require () {
  say "\n>>> $* [required]"
  if "$@" >>"$LOG" 2>&1; then
    say "    OK"
  else
    say "    FAILED - aborting, because later steps depend on this."
    say "    See $LOG for the error."
    exit 1
  fi
}

say "=== regeneration started: $(date) ==="

# ---------------------------------------------------------------------------
# PREFLIGHT. Two files cannot be regenerated by any script in this repository.
# If either is missing the run cannot proceed, and finding that out now is much
# cheaper than finding out after several hours of model fitting.
# ---------------------------------------------------------------------------
say "\n--- preflight ---"
MISSING=0
need () {  # need <path> <how to obtain it>
  if [ -e "$1" ]; then
    say "  present : $1"
  else
    say "  MISSING : $1"
    say "            -> $2"
    MISSING=1
  fi
}

need "../Data/Ganga Basin Shapefile/Ganga_basin.shp" \
     "Basin boundary. NOT regenerable - restore from git or a backup."
need "../Data/Groundwater/gwl_india/Quality_controlled_groundwater_levels_over_India/Output/CGWB_India_filtered_Dug_wells_GWLs_ref_sy_2000_2022.csv" \
     "CGWB wells (Kuruva et al. 2025). NOT regenerable - re-download the 27 MB zip from https://doi.org/10.6084/m9.figshare.29293877 (v3) into Data/Groundwater/gwl_india/"

if [ "$WITH_DOWNLOAD" -eq 0 ]; then
  need "../Data/Outputs/Daily_GEE_GLDAS_V021.csv" \
       "Basin-mean predictors. Re-run with --with-download, or: python gee_download.py"
  need "../Data/Gridded/cubes/grace_cube.nc" \
       "GRACE cube. Re-run with --with-download, or: python gee_gridded_download.py && python build_cube.py"
  need "../Data/Gridded/cubes/era5_cube.nc" \
       "ERA5-Land cube. Re-run with --with-download, or: python gee_gridded_download.py && python build_cube.py"
  need "../Data/Gridded/cubes/grids_aux.nc" \
       "Grid geometry + mascon partition. Re-run with --with-download, or: python build_cube.py"
  need "../Data/Gridded/cubes/static_cube.nc" \
       "Static covariates. Re-run with --with-download, or: python gee_static_download.py && python build_cube.py"
fi

if [ "$MISSING" -ne 0 ]; then
  say "\nPreflight FAILED. Nothing has been run."
  exit 1
fi
say "  preflight OK"

if [ "$CHECK_ONLY" -eq 1 ]; then
  say "\n--check requested; stopping before any work."
  exit 0
fi

# ---------------------------------------------------------------------------
# 0. ACQUISITION (only with --with-download). Slow, hits Earth Engine.
# ---------------------------------------------------------------------------
if [ "$WITH_DOWNLOAD" -eq 1 ]; then
  say "\n--- acquisition (Earth Engine) ---"
  require python gee_download.py            # -> Data/Outputs/Daily_GEE_GLDAS_V0*.csv
  require python gee_gridded_download.py    # -> Data/Gridded/raw/  (~5 GB)
  require python gee_static_download.py     # -> Data/Gridded/static/ (covariates)
  require python build_cube.py              # -> Data/Gridded/cubes/ (incl. static_cube)
fi

# ---------------------------------------------------------------------------
# 1. INPUT TABLES. Everything below reads these.
# ---------------------------------------------------------------------------
say "\n--- inputs ---"

# Predictor table. Reconstructed from the GEE download so its provenance is in
# code rather than in an uncommitted manual step. Skipped if All_Data.xlsx
# already exists, since the shipped copy is the one the manuscript used.
if [ ! -e "../Data/All_Data.xlsx" ]; then
  require python build_all_data.py --write
else
  run python build_all_data.py --verify
fi

# GRACE target, derived from the same gridded mascon product the 0.1 deg
# pipeline uses so both halves rest on one source. EVERYTHING depends on this.
require python export_basin_grace.py --compare

# Independent validation set (never a predictor).
require python wells_ingest.py

# ---------------------------------------------------------------------------
# 2. BASIN-SCALE (temporal downscaling)
# ---------------------------------------------------------------------------
say "\n--- basin-scale ---"
require python run_analysis.py --analysis all --compare
run python generate_monthly_maps.py
run python analyze_results.py --holdout-dir ../Results/figures/temporal_holdout --n-boot 2000
run python analyze_results.py --holdout-dir ../Results/figures/random_holdout --n-boot 2000
run python analyze_results.py --leakage --models randomforest xgboost lightgbm
run python temporal_closure_validation.py --predictions-dir ../Results/figures/temporal_holdout --n-boot 2000

# ---------------------------------------------------------------------------
# 3. GRIDDED (spatial downscaling to 0.1 deg)
# ---------------------------------------------------------------------------
say "\n--- gridded ---"
# Which covariates earn a place, judged on held-out skill rather than on their
# contribution to the fit. Writes covariate_gate_<model>.csv (the evidence
# table) and covariate_survivors.json, which the steps below PICK UP
# AUTOMATICALLY. `require`, not `run`: everything downstream now depends on its
# output, and a silent failure here would leave the product built on whatever
# survivor file happened to be lying around from an earlier configuration.
require python downscale_covariate_gate.py --model xgboost
require python downscale_model.py --model xgboost   # spatial CV + 0.1 deg product
run python downscale_uncertainty.py                 # per-pixel uncertainty ensemble
run python generate_gridded_maps.py                 # maps (uses the uncertainty file if present)
run python validate_wells.py                        # independent well comparison

# 4. DAILY product. Disaggregates the monthly field using ERA5-Land fluxes and
#    states, de-meaned within each month so the monthly means -- and therefore
#    GRACE -- are preserved exactly. Deliberately not an ML step: with no daily
#    target, a daily model would be trained on an interpolation of the monthly
#    product and could only reproduce that assumption.
run python downscale_daily.py

# ---------------------------------------------------------------------------
say "\n=== regeneration finished: $(date) ==="
FAILS=$(grep -c "FAILED" "$LOG" || true)
if [ "$FAILS" -gt 0 ]; then
  say "\n$FAILS step(s) reported FAILED - inspect $LOG before trusting any output:"
  grep -n -B1 "FAILED" "$LOG" | tee -a "$LOG"
  exit 1
fi
say "all steps OK"
